In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
sns.set_style('white')
%matplotlib inline

In [21]:
df = pd.read_csv('small_countries_are_beautiful.csv')
df.head()

,indicator,population,GDP,GDP .1,GDP per km2,land area (sq km),population density,total foreign-born population,% foreign-born population,population living abroad (diaspora),population living abroad,happy planet index,world happiness report score,human development index,health expenditure,education expenditure
0,source,Heritage Foundation,Heritage Foundation,Heritage Foundation,Heritage Foundation,CIA World Factbook,World Bank,UN,UN,UN,UN,Happy Planet Index,World Happiness Report,UNDP,World Bank,our calcs
1,URL,https://www.heritage.org/index/explore,https://www.heritage.org/index/explore,https://www.heritage.org/index/explore,https://www.heritage.org/index/explore,https://www.cia.gov/library/publications/the-w...,https://data.worldbank.org/indicator/EN.POP.DNST,http://www.un.org/en/development/desa/populati...,http://www.un.org/en/development/desa/populati...,http://www.un.org/en/development/desa/populati...,http://www.un.org/en/development/desa/populati...,http://happyplanetindex.org/,http://worldhappiness.report/ed/2018/,http://hdr.undp.org/en/data#,https://data.worldbank.org/indicator/SH.XPD.CH...,NaN
2,notes,NaN,"(billions, PPP)",per capita (PPP),(PPP),NaN,(people per sq km land area),NaN,NaN,NaN,%,NaN,NaN,NaN,per capita (current international $),current US$ per capita
3,data year,2018,2018,"2,018","2,018",2018,2017,"2,015",2015,2015,2015,2016,2017,2017,2015,NaN
4,Albania,"2,900,000",34.20,"11,840","1,248,266","27,398",105,"57,616",3.10,1122910,27.94,20.2,4.64,0.785,774,-

In [22]:
df.drop([0, 1, 2, 3], inplace = True)
df.head()

,indicator,population,GDP,GDP .1,GDP per km2,land area (sq km),population density,total foreign-born population,% foreign-born population,population living abroad (diaspora),population living abroad,happy planet index,world happiness report score,human development index,health expenditure,education expenditure
4,Albania,"2,900,000",34.20,"11,840","1,248,266","27,398",105,"57,616",3.10,1122910,27.94,20.2,4.64,0.785,774,-
5,Armenia,"3,000,000",25.80,"8,621","914,796","28,203",103,"191,199",10.60,937299,23.70,25.7,4.29,0.755,883,89.77
6,Bahamas,"400,000",9.00,"24,555","899,101","10,010",39,"59,306",16.30,40095,9.35,-,-,0.807,1699,-
7,Bahrain,"1,300,000",66.90,"50,704","88,026,316",760,1936,"704,137",54.70,55964,4.00,-,6.23,0.846,2453,616.5
8,Barbados,"300,000",4.80,"17,100","11,162,791",430,664,"34,475",11.30,98464,26.16,-,-,0.800,1234,1013.0

In [25]:
df.rename(columns = {'indicator': 'Countries', 'population': 'Population (2018)', 
                    'GDP': 'GDP (2018)', 'GDP .1': 'GDP .1 (2018)', 
                     'GDP per km2': 'GDP(sq km)', 
                     'land area (sq km)': 'Land Area(sq km) (2018)',
                    'population density': 'Population Density(sq km) (2017)', 
                    'total foreign-born population': 'Total foreign-born population (2015)', 
                    '% foreign-born population': 'Percentage of foreign-born population (2015)', 
                    'population living abroad (diaspora)': 'Diaspora (2015)', 
                    'population living abroad': 'Population living abroad (2015)', 
                    'happy planet index': 'Happy Planet Index (2016)', 
                    'world happiness report score': 'World Happiness Report Score (2017)', 
                    'human development index': 'HDI (2017)', 
                    'health expenditure': 'Health expenditure (2015)', 
                    'education expenditure': 'Education expenditure'}, inplace = True)
df.head().reset_index(drop = True)

,Countries,Population (2018),GDP,GDP .1 (2018),GDP per km2,Land Area(sq km) (2018),population density,total foreign-born population,Percentage of foreign-born population (2015),Diaspora (2015),population living abroad,Happy Planet Index (2016),World Happiness Report Score (2017),HDI (2017),health expenditure,education expenditure
0,Albania,"2,900,000",34.20,"11,840","1,248,266","27,398",105,"57,616",3.10,1122910,27.94,20.2,4.64,0.785,774,-
1,Armenia,"3,000,000",25.80,"8,621","914,796","28,203",103,"191,199",10.60,937299,23.70,25.7,4.29,0.755,883,89.77
2,Bahamas,"400,000",9.00,"24,555","899,101","10,010",39,"59,306",16.30,40095,9.35,-,-,0.807,1699,-
3,Bahrain,"1,300,000",66.90,"50,704","88,026,316",760,1936,"704,137",54.70,55964,4.00,-,6.23,0.846,2453,616.5
4,Barbados,"300,000",4.80,"17,100","11,162,791",430,664,"34,475",11.30,98464,26.16,-,-,0.800,1234,1013.0